/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleH.js
 */

#pragma once

#include <ReactCommon/TurboModule.h>
#include <react/bridging/Bridging.h>

namespace facebook::react {


template <typename T>
class JSI_EXPORT NativeStdIOCxxSpec : public TurboModule {
public:
  static constexpr std::string_view kModuleName = "NativeStdIO";

protected:
  NativeStdIOCxxSpec(std::shared_ptr<CallInvoker> jsInvoker) : TurboModule(std::string{NativeStdIOCxxSpec::kModuleName}, jsInvoker) {
    methodMap_["createFileSystem"] = MethodMetadata {.argCount = 1, .invoker = __createFileSystem};
    methodMap_["createIORequest"] = MethodMetadata {.argCount = 0, .invoker = __createIORequest};
    methodMap_["createPlatform"] = MethodMetadata {.argCount = 0, .invoker = __createPlatform};
    methodMap_["installHttpClient"] = MethodMetadata {.argCount = 0, .invoker = __installHttpClient};
  }
  
private:
  static jsi::Value __createFileSystem(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::createFileSystem) == 2,
      "Expected createFileSystem(...) to have 2 parameters");
    return bridging::callFromJs<jsi::Object>(rt, &T::createFileSystem,  static_cast<NativeStdIOCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asNumber());
  }

  static jsi::Value __createIORequest(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::createIORequest) == 1,
      "Expected createIORequest(...) to have 1 parameters");
    return bridging::callFromJs<jsi::Object>(rt, &T::createIORequest,  static_cast<NativeStdIOCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));
  }

  static jsi::Value __createPlatform(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::createPlatform) == 1,
      "Expected createPlatform(...) to have 1 parameters");
    return bridging::callFromJs<jsi::Object>(rt, &T::createPlatform,  static_cast<NativeStdIOCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));
  }

  static jsi::Value __installHttpClient(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::installHttpClient) == 1,
      "Expected installHttpClient(...) to have 1 parameters");
    bridging::callFromJs<void>(rt, &T::installHttpClient,  static_cast<NativeStdIOCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));return jsi::Value::undefined();
  }
};

} // namespace facebook::react
